import type { Config } from 'tailwindcss';

export default {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './app.vue',
    './error.vue',
  ],
  theme: {
    extend: {
      colors: {
        // Aether Glass – Aether Glass color tokens
        'on-secondary-container': '#aeb9d0',
        'on-tertiary-fixed-variant': '#004e5a',
        'primary-container': '#4446d2',
        'outline-variant': '#454652',
        secondary: '#bcc7de',
        'primary-fixed-dim': '#c0c1ff',
        'on-tertiary': '#00363e',
        'inverse-surface': '#dae2fd',
        'on-error': '#690005',
        'surface-dim': '#0b1326',
        'surface-container-low': '#131b2e',
        'tertiary-container': '#006472',
        'on-surface-variant': '#c5c5d4',
        'on-primary-container': '#ceceff',
        'on-tertiary-fixed': '#001f25',
        'surface-tint': '#c0c1ff',
        'secondary-fixed': '#d8e3fb',
        error: '#ffb4ab',
        'on-secondary': '#263143',
        'on-secondary-fixed-variant': '#3c475a',
        tertiary: '#2fd9f4',
        'surface-bright': '#31394d',
        'on-background': '#dae2fd',
        'on-primary': '#1000a9',
        'primary-fixed': '#e1e0ff',
        'on-secondary-fixed': '#111c2d',
        'secondary-container': '#3e495d',
        'inverse-on-surface': '#283044',
        outline: '#8f909e',
        'on-error-container': '#ffdad6',
        'secondary-fixed-dim': '#bcc7de',
        background: '#0b1326',
        'surface-container-high': '#222a3d',
        'surface-container-lowest': '#060e20',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#2f2ebe',
        'tertiary-fixed-dim': '#2fd9f4',
        surface: '#0b1326',
        'on-primary-fixed': '#07006c',
        'on-tertiary-container': '#50e5ff',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'surface-variant': '#2d3449',
        'tertiary-fixed': '#a2eeff',
        primary: '#c0c1ff',
        'surface-container': '#171f33',
        'inverse-primary': '#494bd6',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
        sans: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.6s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      boxShadow: {
        glass: '0 10px 40px rgba(7, 0, 108, 0.15)',
      },
    },
  },
  plugins: [],
} satisfies Config;
