// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/26/2026, 7:47:50 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/plugins/**/*.{js,ts,mjs}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/composables/**/*.{js,ts,mjs}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/composables/**/**/*.{js,ts,mjs}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/utils/**/*.{js,ts,mjs}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/stores/**/*.{js,ts,mjs}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/bharath/Documents/GitHub/nuxt3-article-dashboard/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;